### ISSUE TITLE
Problems with NLPentities

### ISSUE THREAD

**Issue by nicolasschwab** [mark-watson/nlp_smalltalk#1]
Hi buddy, first of all thanks for code, it's been really helpfull. 
But i have been having a problem with the NLPentities, i have tried the examples you propose in the readme and a few more but when i print de result of :
NLPentities initializeEntities.
NLPentities entities: 'The Coca Cola factory is in London Clipperton Island' . 

for example i get only this:   a Dictionary('places'->a Set('Clipperton Island' 'London') ).

Any thoughts?
Cheers nicolas

**Comment by mark-watson** [comment]
Hello. Please try other example input sentences with common place names, well known people, etc.

I got the following results:

a Dictionary('companies'->a Set('Coca Cola') 'places'->a Set('Clipperton Island' 'London') 'products'->a Set('Coca Cola') )

I don't have tme right now, but I will try installing a fresh Pharo 4, and filing in what is at https://github.com/mark-watson/nlp_smalltalk

**Comment by nicolasschwab** [comment]
Hi mark. Thanks fpr the answer, actually i didn't think you would reply jajaja. Any way i found the problem, it turns out that the code has some problems in Windows, i changed to linux and it worked just fine.
Cheers.
Nicolas

Enviado desde mi Windows Phone

---

De: Mark Watsonmailto:notifications@github.com
Enviado el: ‎02/‎12/‎2015 09:30 p.m.
Para: mark-watson/nlp_smalltalkmailto:nlp_smalltalk@noreply.github.com
CC: nicolasschwabmailto:nicolasschwab2@hotmail.com
Asunto: Re: [nlp_smalltalk] Problems with NLPentities (#1)

Hello. Please try other example input sentences with common place names, well known people, etc.

I got the following results:

a Dictionary('companies'->a Set('Coca Cola') 'places'->a Set('Clipperton Island' 'London') 'products'->a Set('Coca Cola') )

I don't have tme right now, but I will try installing a fresh Pharo 4, and filing in what is at https://github.com/mark-watson/nlp_smalltalk

---
